- name: Install pip.
  apt:
    pkg=python-pip
    state=latest
    update_cache=yes
    cache_valid_time=86400
  sudo: yes

- name: Install docutils for Python to build documentation.
  pip:
    name=docutils
  sudo: yes
