---
# This Ansible role prepares OOMMF examples and places some documentation on
# the Desktop.

# Create examples documentation.
- name: Create documentation build directory.
  file:
    name={{ EXAMPLES_DOC_FOLDER }}
    state=directory
  sudo: yes

- name: Convert to HTML and place in the build directory.
  shell: rst2html.py {{ EXAMPLES_RST_FILE }} {{ EXAMPLES_OUTPUT_NAME }}
    chdir={{ EXAMPLES_DOC_FOLDER }}
    creates={{ EXAMPLES_DOC_FOLDER }}/{{ EXAMPLES_OUTPUT_NAME }}
  sudo: yes

# This task is not very robust, but I can't think of a better way of doing
# this.
- name: Copy oommf examples to a more accessible location.
  command: cp -r /opt/oommf/oommf-1.2a5bis/app/oxs/examples {{ OOMMF_EXAMPLES_FOLDER }}
    creates={{ OOMMF_EXAMPLES_FOLDER }}
  sudo: yes