---
# This Ansible role prepares Nmag examples and places some documentation on the
# Desktop.

# Create examples documentation.
- name: Create documentation build directory.
  file:
    name={{ EXAMPLES_DOC_FOLDER }}
    state=directory
  sudo: yes

- name: Convert to HTML and place in the build directory.
  shell: rst2html.py {{ EXAMPLES_RST_FILE }} {{ EXAMPLES_OUTPUT_NAME }}
    chdir={{ EXAMPLES_DOC_FOLDER }}
    creates={{ EXAMPLES_DOC_FOLDER }}/{{ EXAMPLES_OUTPUT_NAME }}
  sudo: yes

# This following task is not very robust, but I can't think of a better way of
# doing this.
- name: Copy nmag examples to a more accessible location.
  command: cp -r /opt/nmag/nmag-0.2.1/doc/html/_downloads {{ NMAG_EXAMPLES_FOLDER }}
    creates={{ NMAG_EXAMPLES_FOLDER }}
  sudo: yes