---
# This Ansible playbook creates a virtual machine using vagrant and the
# Vagrantfile template.

- name: Define a directory for the vagrant environment for this machine to inhabit. It will be the directory of the Makefile concatenated with the name of the machine.
  set_fact:
    vm_dir: "{{ lookup('pipe','pwd') }}/../../../machines/{{ vm_name }}-vm"

- name: Ensure that a directory is created for the virtual machine.
  file:
    name={{ vm_dir }}
    state=directory

- name: Place the Vagrantfile in the virtual machine directory.
  template:
    src=Vagrantfile
    dest={{ vm_dir }}

- name: Check the status of virtual machine and store it.
  command: vagrant status
    chdir={{ vm_dir }}
  register: status
  changed_when: false

- name: Destroy the virtual machine if its status suggests it exists and it is desired to do so.
  command: vagrant destroy --force
    chdir={{ vm_dir }}
  when: (not "not created" in status.stdout) and destroy_existing_vm

- name: Copy the provisioning playbook to the virtual machine directory.
  copy:
    src={{ playbook_root_dir }}/{{ playbook }}
    dest={{ vm_dir }}

- name: Copy the extra resources directory to the virtual machine directory if it was specified.
  copy:
    src={{ extra_resources_dir }}/
    dest={{ vm_dir }}/extra_resources
  when: extra_resources_dir is defined

- name: Add the roles directory of this repository to the ansible configuration in the virtual machine directory so that roles can be found.
  ini_file:
    dest={{ vm_dir }}/ansible.cfg
    section=defaults
    option=roles_path
    value={{ lookup('pipe','pwd') }}/../..

- name: Obtain the current tag, (or version if untagged) of this repository.
  shell: |
    TAG=$(git name-rev --tags --name-only HEAD | cut -f1 -d^)
    if [ "$(echo $TAG | tr -d [:space:])" == "undefined" ]; then
        git rev-parse --short HEAD
    else
        echo $TAG
    fi
  args:
    chdir: "{{ vm_dir }}"
    executable: /bin/bash
  register: current_version

- name: Store this version or tag in a file so that the virtual machine can access it.
  lineinfile:
    dest={{ vm_dir }}/repository_version
    create=yes
    state=present
    regexp="^[0-9a-zA-Z]*"
    line={{ current_version.stdout }}

- name: Obtain build machine information.
  shell: |
    echo "Build VirtualBox version: $(VBoxManage --version)" > {{ vm_dir }}/build_information
    echo "Build Vagrant version: $(vagrant --version)" >> {{ vm_dir }}/build_information
    echo "Build hostname: $HOSTNAME" >> {{ vm_dir }}/build_information
    echo "Uname output: $(uname -a)" >> {{ vm_dir }}/build_information
    echo "lsb_release output: $(lsb_release -a)" >> {{ vm_dir }}/build_information
  args:
    chdir: "{{ vm_dir }}"
    executable: /bin/bash

- name: Start the virtual machine. Vagrant may attempt to install VirtualBox Guest Additions here.
  shell: vagrant up --no-provision > {{ vm_name }}.log
    chdir={{ vm_dir }}

- name: Provision the virtual machine. A log exists in machines/.
  shell: vagrant provision >> {{ vm_name }}.log
    chdir={{ vm_dir }}

- name: Install VirtualBox Guest Additions.
  command: vagrant vbguest --auto-reboot --no-provision --do install
    chdir={{ vm_dir }}

- name: Run post-build hooks if a hookbook has been passed.
  include: "../../../{{ playbook_root_dir }}/{{ hookbook }}"
  when: hookbook is defined