---
# This Ansible include-playbook clones Fidimag source.

- name: Ensure that Git and openssh-client are installed.
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - git
    - openssh-client
  sudo: yes

- name: Clone the Fidimag source.
  git:
    repo: "{{ FIDIMAG_REPO_URL }}"
    dest: "{{ FIDIMAG_INSTALL_PATH }}"
    version: "{{ FIDIMAG_VERSION }}"
  sudo: yes
