---
# This Ansible playbook build Fidimag from scripts in the Fidimag
# repository. This include installing local dependencies including FFTW and
# SUNDIALS.

# Install local dependencies.
- name: Install FFTW and SUNDIALS from Fidimag installation scripts.
  command: bash {{ item }}
  args:
    chdir: "{{ FIDIMAG_INSTALL_PATH }}/bin"
  with_items:
    - install-fftw.sh
    - install-sundials-2.5.sh
  sudo: yes

# Build Fidimag. Makefile module?
- name: Build Fidimag.
  command: make
  args:
    chdir: "{{ FIDIMAG_INSTALL_PATH }}"
  sudo: yes
