---
# This Ansible include-playbook sets envionment variables which denote
# essential paths for Fidimag.

- name: Add Fidimag to PYTHONPATH.
  lineinfile:
    dest: /etc/profile.d/fidimag.sh
    regexp: "^export PYTHONPATH="
    line: "export PYTHONPATH=\"{{ FIDIMAG_INSTALL_PATH }}/:$PYTHONPATH\""
    create: yes
  sudo: yes
