# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.port = 22
  config.ssh.username = "root"
  config.ssh.password = "virtualmicromagnetics"

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
    d.name = "{{ container_name }}"
  end

  config.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {type: "container"}
      ansible.playbook = "{{ playbook }}"
      ansible.verbose = "vvvv"
  end
end
