- name: In file 'Makefile.in.defaults', set variable 'MAGPAR_HOME' to the desired installation location
  lineinfile:
    dest="{{ MAGPAR_INSTALL_PREFIX }}/{{ MAGPAR_EXTRACTED_DIR.stdout }}/src/Makefile.in.defaults"
    regexp="^MAGPAR_HOME.*="
    line="MAGPAR_HOME={{ MAGPAR_INSTALL_PREFIX }}/{{ MAGPAR_EXTRACTED_DIR.stdout }}"
  sudo: yes

- name: Copy Magpar patches
  copy:
    src={{ item }}
    dest={{ MAGPAR_INSTALL_PREFIX }}/{{ MAGPAR_EXTRACTED_DIR.stdout }}/src/
  with_items:
    - magpar.patch
    - magpar_code.patch
    - magpar_Makefile_libs.patch
  sudo: yes

- name: Apply patches to Magpar source
  patch:
    src={{ MAGPAR_INSTALL_PREFIX }}/{{ MAGPAR_EXTRACTED_DIR.stdout }}/src/{{ item }}
    basedir={{ MAGPAR_INSTALL_PREFIX }}/{{ MAGPAR_EXTRACTED_DIR.stdout }}/src/
    remote_src=True
  with_items:
    - magpar.patch
    - magpar_code.patch
    - magpar_Makefile_libs.patch
  sudo: yes
