- name: Install gfortran package required by Magpar
  apt:
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=86400
  with_items:
    - patch
    - gfortran
    - g++
    - liblapack-dev
    - mpich2
  sudo: yes
