---
# This Ansible playbook is a provision playbook designed to be used with
# vagrant. This playbook provisions a machine suitable for micromagnetic
# simulation with OOMMF. It is executed by the virtual machine.

- hosts: all

  vars:
    vm_name: virtualmicromagnetics-oommf

  roles:
    - oommf
    - oommf_examples
    - xserver
    - rst_to_html
    - add_super_user
    - { role: set_hostname, HOSTNAME: {{ vm_name }} }
