---
# This Ansible playbook is a provision playbook designed to be used with
# vagrant. This playbook provisions a machine suitable for micromagnetic
# simulation with OOMMF. It is executed by the virtual machine.

- hosts: all

  roles:
    - oommf
    - oommf_examples
    - xserver
    - rst_to_html
    - { role: add_super_user, AUTOLOGIN: true }
    - { role: set_hostname, HOSTNAME: virtualmicromagnetics-oommf }
