---
# This Ansible playbook is a provision playbook designed to be used with
# vagrant. This playbook provisions a machine suitable for micromagnetic
# simulation with nmag. It is executed by the virtual machine.

- hosts: all

  vars:
    vm_name: virtualmicromagnetics-nmag

  roles:
    - write_characteristics_file
    - { role: rst_to_html, SOURCE_PATH: "/vagrant/extra_resources/welcome/welcome_{{ vm_name }}.rst" }
    - nmag
    - nmag_examples
    - xserver
    - add_super_user
    - { role: set_hostname, HOSTNAME: "{{ vm_name }}" }
