---
# This Ansible playbook is a provision playbook designed to be used with
# vagrant. This playbook provisions a machine suitable for micromagnetic
# simulation, and includes other convenient softwares for such an
# environment. It is executed by the virtual machine.

- hosts: all

  roles:
    - fidimag
    - xserver
    - rst_to_html
    - add_super_user
    - { role: set_hostname, HOSTNAME: virtualmicromagnetics-fidimag }
