- name: Download Nmag tarball to NMAG_DOWNLOAD_FOLDER
  get_url:
     url={{NMAG_URL}}
     dest={{NMAG_DOWNLOAD_FOLDER}}/{{NMAG_TARBALL}}
     sha256sum=b69642508922b5639339a2f658bcc058412d04154e548e041b3621c4404540c3
  sudo: yes

- name: Determine directory name of Nmag tarball to be extracted
  shell: "tar tzf {{NMAG_DOWNLOAD_FOLDER}}/{{NMAG_TARBALL}} | head -1 | sed -e 's|/.*||'"
  register: NMAG_EXTRACTED_DIR
  changed_when: false

- name: Ensure the directory NMAG_INSTALL_PREFIX exists
  file:
    path={{NMAG_INSTALL_PREFIX}}
    state=directory
  sudo: yes

# We use an explicit 'tar' invocation here (rather than ansible's built-in 'unarchive' functionality)
# to ensure that the permissions are set correctly.
- name: Extract Nmag tarball in NMAG_INSTALL_PREFIX
  command: tar --no-same-permissions --no-same-owner -xzf {{NMAG_DOWNLOAD_FOLDER}}/{{NMAG_TARBALL}} -C {{NMAG_INSTALL_PREFIX}}
    creates={{NMAG_INSTALL_PREFIX}}/{{NMAG_EXTRACTED_DIR.stdout}}
  sudo: yes

- name: Make sure the extracted files are readable by all users
  command: chmod -R a+r {{NMAG_INSTALL_PREFIX}}/{{NMAG_EXTRACTED_DIR.stdout}}
  sudo: yes
