- name: Install Nmag dependencies
  apt:
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=86400
  with_items:
    - dpkg-dev
    - g++
    - gawk
    - libblas-dev
    - liblapack-dev
    - libreadline-dev
    - m4
    - make
    - mpich
    - readline-common
    - zlib1g-dev
  sudo: yes