---
# This Ansible playbook runs Nmag tests.

- name: Configure Nmag to run tests.
  command: "{{ NMAG_INSTALL_PREFIX }}/{{ NMAG_VERSION }}/nsim/bin/nsim {{ NMAG_INSTALL_PREFIX }}/{{ NMAG_VERSION }}/nsim/tests/config/setup.py"
  args:
    chdir: "{{ NMAG_INSTALL_PREFIX }}/{{ NMAG_VERSION }}/nsim/tests/config"
  sudo: yes

- name: Run tests.
  command: make test
  args:
    chdir: "{{ NMAG_INSTALL_PREFIX }}/{{ NMAG_VERSION }}/tests"
  environment:
    PATH: "$PATH:{{ NMAG_INSTALL_PREFIX }}/{{ NMAG_VERSION }}/nsim/bin"
  sudo: yes