- name: Install dependencies Tcl and Tk required by OOMMF
  apt:
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=86400
  with_items:
    - tk{{ TCLTKVERSION }}-dev
    - tcl{{ TCLTKVERSION }}-dev
    - dpkg-dev
  sudo: yes
